 <div id="site_container" class="centered overflow">     
    
    <div class="row">
        <h2 class="arimo">This is a heading</h2>
        <p class="grid_6">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In justo elit, ullamcorper vel faucibus ac, posuere id nisl. Mauris scelerisque, erat vitae dapibus adipiscing, diam eros sollicitudin nibh, ut tincidunt eros turpis sit amet urna. Donec a risus lectus, vitae porttitor arcu. Nunc non pulvinar tortor. Sed aliquet quam consequat metus aliquet rhoncus. Maecenas semper velit ac mauris euismod consequat. Aliquam quis nisi ac massa viverra pellentesque. In hac habitasse platea dictumst. Sed vitae leo purus, sed porttitor dolor. Pellentesque et diam non mauris sodales vehicula non ac turpis. Nunc nec purus quis sem congue egestas eu sed ante. </p>
        <p class="grid_6">Vestibulum non dolor diam, nec elementum velit. Vestibulum nibh dui, elementum sed sagittis et, semper vitae nunc. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque non erat dui. Donec vestibulum augue a urna tincidunt in scelerisque risus aliquam. Nulla facilisi. Quisque non neque ac ipsum faucibus tempus id sit amet magna. Etiam sed est ut est ornare blandit. Praesent faucibus interdum massa quis mattis. Ut tincidunt, lacus id interdum egestas, lectus turpis pellentesque enim, at egestas mi leo ut nisi. Sed gravida, justo non blandit tincidunt, risus mi pharetra nisi, suscipit consequat tortor leo sit amet nunc. Aliquam vestibulum enim eu metus dapibus at euismod sem luctus. </p>
    </div>
     
     <div id="portfolio_slideshow">  
                
         <div class="row">
             <a class="portfolio_link grid_6" href="http://deals.parents.com/national"><img src="{$cdn}/images/parents-460.png" width="452" height="452" /></a>
             <h2 class="parents_highlight grid_6">Deals.Parents.com</h2>
             <p class="grid_6">Suspendisse et libero sit amet massa sagittis tristique. Ut id fringilla quam. Ut sollicitudin purus et metus ornare tempor. Etiam ante nisl, sodales eget facilisis varius, imperdiet quis ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi euismod luctus velit, dictum aliquam dui cursus non. Sed egestas congue suscipit. Vivamus pellentesque facilisis vehicula. Nulla facilisi. Donec lobortis, odio tincidunt auctor tempor, nisl quam adipiscing lorem, volutpat pulvinar augue libero ac purus. Donec venenatis laoreet nibh in varius. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu leo sit amet massa consectetur consectetur vitae sit amet mi. Vestibulum purus nisi, pulvinar volutpat condimentum eu, faucibus quis odio. Morbi faucibus magna sagittis urna mattis pretium. Vestibulum elementum cursus sagittis. </p> 
         <p class="grid_6">Integer porta fringilla ultrices. Nam in dolor ac magna sollicitudin ultricies vitae sit amet arcu. Suspendisse turpis elit, vehicula blandit feugiat in, elementum vitae tellus. Duis urna felis, lobortis at tempus eu, tempor sit amet nulla. Donec tempus dapibus nisl, sit amet mattis risus porta eget. Nulla eu consectetur ipsum. Mauris placerat sem eu nulla viverra egestas euismod purus pulvinar. Praesent justo tortor, accumsan quis cursus a, ultricies sit amet est. Ut risus turpis, condimentum at convallis ut, tristique et nunc. Vivamus ultricies egestas erat id tempor.</p>
      </div>
          
      <div class="row">
         <a class="portfolio_link grid_6" href="http://allmenus.com"><img src="{$cdn}/images/allmenus-460.png" width="460" height="460" /></a>
         <h2 class="am_highlight grid_6">Allmenus.com</h2>
         <p class="grid_6">Suspendisse et libero sit amet massa sagittis tristique. Ut id fringilla quam. Ut sollicitudin purus et metus ornare tempor. Etiam ante nisl, sodales eget facilisis varius, imperdiet quis ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi euismod luctus velit, dictum aliquam dui cursus non. Sed egestas congue suscipit. Vivamus pellentesque facilisis vehicula. Nulla facilisi. Donec lobortis, odio tincidunt auctor tempor, nisl quam adipiscing lorem, volutpat pulvinar augue libero ac purus. Donec venenatis laoreet nibh in varius. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu leo sit amet massa consectetur consectetur vitae sit amet mi. Vestibulum purus nisi, pulvinar volutpat condimentum eu, faucibus quis odio. Morbi faucibus magna sagittis urna mattis pretium. Vestibulum elementum cursus sagittis. </p> 
         <p class="grid_6">Integer porta fringilla ultrices. Nam in dolor ac magna sollicitudin ultricies vitae sit amet arcu. Suspendisse turpis elit, vehicula blandit feugiat in, elementum vitae tellus. Duis urna felis, lobortis at tempus eu, tempor sit amet nulla. Donec tempus dapibus nisl, sit amet mattis risus porta eget. Nulla eu consectetur ipsum. Mauris placerat sem eu nulla viverra egestas euismod purus pulvinar. Praesent justo tortor, accumsan quis cursus a, ultricies sit amet est. Ut risus turpis, condimentum at convallis ut, tristique et nunc. Vivamus ultricies egestas erat id tempor.</p>
      </div>
         
      <div class="row">
         <a class="portfolio_link grid_6" href="http://neilgirardi.com/portfolio/celsius"><img src="{$cdn}/images/celsius-460.png"  width="460" height="460" /></a>
         <h2 class="celsius_highlight grid_6">Celsius.com</h2>
         <p class="grid_6">Suspendisse et libero sit amet massa sagittis tristique. Ut id fringilla quam. Ut sollicitudin purus et metus ornare tempor. Etiam ante nisl, sodales eget facilisis varius, imperdiet quis ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi euismod luctus velit, dictum aliquam dui cursus non. Sed egestas congue suscipit. Vivamus pellentesque facilisis vehicula. Nulla facilisi. Donec lobortis, odio tincidunt auctor tempor, nisl quam adipiscing lorem, volutpat pulvinar augue libero ac purus. Donec venenatis laoreet nibh in varius. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu leo sit amet massa consectetur consectetur vitae sit amet mi. Vestibulum purus nisi, pulvinar volutpat condimentum eu, faucibus quis odio. Morbi faucibus magna sagittis urna mattis pretium. Vestibulum elementum cursus sagittis. </p> 
         <p class="grid_6">Integer porta fringilla ultrices. Nam in dolor ac magna sollicitudin ultricies vitae sit amet arcu. Suspendisse turpis elit, vehicula blandit feugiat in, elementum vitae tellus. Duis urna felis, lobortis at tempus eu, tempor sit amet nulla. Donec tempus dapibus nisl, sit amet mattis risus porta eget. Nulla eu consectetur ipsum. Mauris placerat sem eu nulla viverra egestas euismod purus pulvinar. Praesent justo tortor, accumsan quis cursus a, ultricies sit amet est. Ut risus turpis, condimentum at convallis ut, tristique et nunc. Vivamus ultricies egestas erat id tempor.</p>
      </div>
  
  <div class="row">
         <a class="portfolio_link grid_6" href="http://neilgirardi.com/portfolio/jqueryplugin"><img src="{$cdn}/images/easy-expand-460.png" width="460" height="460" /></a>
         <h2 class="easyexpand_highlight grid_6">EasyExpand()</h2>
         <p class="grid_6">Suspendisse et libero sit amet massa sagittis tristique. Ut id fringilla quam. Ut sollicitudin purus et metus ornare tempor. Etiam ante nisl, sodales eget facilisis varius, imperdiet quis ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi euismod luctus velit, dictum aliquam dui cursus non. Sed egestas congue suscipit. Vivamus pellentesque facilisis vehicula. Nulla facilisi. Donec lobortis, odio tincidunt auctor tempor, nisl quam adipiscing lorem, volutpat pulvinar augue libero ac purus. Donec venenatis laoreet nibh in varius. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu leo sit amet massa consectetur consectetur vitae sit amet mi. Vestibulum purus nisi, pulvinar volutpat condimentum eu, faucibus quis odio. Morbi faucibus magna sagittis urna mattis pretium. Vestibulum elementum cursus sagittis. </p> 
         <p class="grid_6">Integer porta fringilla ultrices. Nam in dolor ac magna sollicitudin ultricies vitae sit amet arcu. Suspendisse turpis elit, vehicula blandit feugiat in, elementum vitae tellus. Duis urna felis, lobortis at tempus eu, tempor sit amet nulla. Donec tempus dapibus nisl, sit amet mattis risus porta eget. Nulla eu consectetur ipsum. Mauris placerat sem eu nulla viverra egestas euismod purus pulvinar. Praesent justo tortor, accumsan quis cursus a, ultricies sit amet est. Ut risus turpis, condimentum at convallis ut, tristique et nunc. Vivamus ultricies egestas erat id tempor.</p>
      </div>
      
  </div>
     
</div> <!-- end of #siteContainer -->